# ports/inbound/i_encounter_service.py
from typing import Protocol
from ...application.dto.encounter_dto import EncounterStateDTO, MonsterSummaryDTO

class IEncounterService(Protocol):
    def add_monster(self, monster_id: str) -> EncounterStateDTO: ...
    def add_player(self, name: str, initiative: int) -> EncounterStateDTO: ...
    def remove_entity(self, instance_id: str) -> EncounterStateDTO: ...
    def edit_hp(self, instance_id: str, new_hp: int) -> EncounterStateDTO: ...
    def toggle_condition(self, instance_id: str, condition_name: str) -> EncounterStateDTO: ...
    def change_initiative(self, instance_id: str, new_initiative: int) -> EncounterStateDTO: ...
    def rename_entity(self, instance_id: str, new_name: str) -> EncounterStateDTO: ...
    def advance_turn(self) -> EncounterStateDTO: ...
    def undo(self) -> EncounterStateDTO: ...
    def get_state(self) -> EncounterStateDTO: ...
    def get_monster_definition(self, monster_id: str) -> MonsterSummaryDTO | None: ...
    def import_monsters(self, json_path: str) -> dict[str, int]: ...
    def list_monsters(self) -> list[MonsterSummaryDTO]: ...
