# adapters/outbound/srd_monster_repository.py
"""
Read-only repository that loads the bundled 5e SRD bestiary
generated by utilities/import_srd_monsters.py
"""

from __future__ import annotations
import json
from pathlib import Path
from typing import Any

from dnd_encounter.domain.entities.monster_definition import MonsterDefinition
from dnd_encounter.ports.outbound.i_monster_repository import IMonsterRepository


class SrdMonsterRepository(IMonsterRepository):
    """
    Loads the large 5e SRD + supplements bestiary from data/srd/monsters.json.
    This is a read-only source. Custom monsters should go through JsonMonsterRepository.
    """

    def __init__(self, path: Path | None = None):
        if path is None:
            candidates = []

            # 1. Explicit project root relative (when running from source with uv run python run_ui.py)
            try:
                base = Path(__file__).resolve().parents[4]
                candidates.append(base / "data" / "srd" / "monsters.json")
            except Exception:
                pass

            # 2. Current working directory (very common when people run from project root)
            candidates.append(Path.cwd() / "data" / "srd" / "monsters.json")

            # 3. One level up from cwd (in case they run from inside src or tests)
            candidates.append(Path.cwd().parent / "data" / "srd" / "monsters.json")

            # Pick the first one that actually exists
            for candidate in candidates:
                if candidate.exists():
                    path = candidate
                    break
            else:
                # Last resort — use the most likely one so we can give a good error message later
                path = candidates[0] if candidates else Path("data/srd/monsters.json")

        self.path = path
        self._cache: list[dict[str, Any]] | None = None

    def _load(self) -> list[dict[str, Any]]:
        if self._cache is not None:
            return self._cache

        if not self.path.exists():
            print(f"[MonsterRepo] WARNING: SRD bestiary not found at {self.path} (cwd={Path.cwd()}). "
                  f"Only custom monsters from the user DB will be available.")
            self._cache = []
            return self._cache
        else:
            print(f"[MonsterRepo] Loading SRD bestiary from {self.path}")

        with open(self.path, encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, list):
            self._cache = data
        else:
            self._cache = []

        return self._cache

    def _safe_monster(self, item: dict[str, Any]) -> MonsterDefinition | None:
        """Best-effort conversion from the importer's JSON to MonsterDefinition."""
        try:
            cr = item.get("challenge_rating")
            if isinstance(cr, dict):
                cr_value = cr.get("value", "0")
            else:
                cr_value = str(cr) if cr else "0"

            from dnd_encounter.domain.value_objects.challenge_rating import ChallengeRating
            cr_obj = ChallengeRating(cr_value)

            abil = item.get("ability_scores", {})
            ability = {
                "str_": abil.get("str_", abil.get("str", 10)),
                "dex": abil.get("dex", 10),
                "con": abil.get("con", 10),
                "int_": abil.get("int_", abil.get("int", 10)),
                "wis": abil.get("wis", 10),
                "cha": abil.get("cha", 10),
            }

            spd = item.get("speed", {})
            speed = {
                "walk": spd.get("walk", 30),
                "fly": spd.get("fly", 0),
                "swim": spd.get("swim", 0),
                "climb": spd.get("climb", 0),
                "burrow": spd.get("burrow", 0),
                "hover": bool(spd.get("hover", False)),
            }

            payload = {
                "id": item.get("id"),
                "name": item.get("name"),
                "size": item.get("size", "Medium"),
                "type_": item.get("type_", "unknown"),
                "alignment": item.get("alignment", "unaligned"),
                "armor_class": item.get("armor_class", 10),
                "hit_points": item.get("hit_points", 10),
                "hit_dice": item.get("hit_dice", "1d8"),
                "speed": speed,
                "ability_scores": ability,
                "challenge_rating": cr_obj,
                "xp": item.get("xp", 0),
                "source": item.get("source", "SRD"),

                # Rich new fields
                "saving_throws": item.get("saving_throws", {}),
                "skills": item.get("skills", {}),
                "damage_resistances": item.get("damage_resistances", []),
                "damage_immunities": item.get("damage_immunities", []),
                "damage_vulnerabilities": item.get("damage_vulnerabilities", []),
                "condition_immunities": item.get("condition_immunities", []),
                "senses": item.get("senses", {}),
                "languages": item.get("languages", []),
                "traits": item.get("traits", []),
                "actions": item.get("actions", []),
                "bonus_actions": item.get("bonus_actions", []),
                "reactions": item.get("reactions", []),
                "legendary_actions": item.get("legendary_actions", []),
                "spellcasting": item.get("spellcasting", []),
                "environments": item.get("environments", []),

                # Image metadata
                "has_token": bool(item.get("has_token")),
                "has_fluff_image": bool(item.get("has_fluff_image")),
                "image_path": item.get("image_path"),
            }

            return MonsterDefinition(**payload)  # type: ignore[arg-type]
        except Exception:
            return None

    def get(self, monster_id: str) -> MonsterDefinition | None:
        for item in self._load():
            if item.get("id") == monster_id:
                m = self._safe_monster(item)
                if m is not None:
                    return m
        return None

    def list_all(self) -> list[MonsterDefinition]:
        result: list[MonsterDefinition] = []
        for item in self._load():
            m = self._safe_monster(item)
            if m is not None:
                result.append(m)
        return result

    def upsert(self, monster: MonsterDefinition) -> None:
        raise NotImplementedError("SrdMonsterRepository is read-only.")

    def count(self) -> int:
        """Return only monsters that successfully converted (not raw JSON length)."""
        return len(self.list_all())